### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by gf3** [romeovs/react-a11y#3]
I believe I'm getting many false positives for elements that shouldn't have any warnings. As well I'm getting some errors when components are re-rendered.

![screen shot 2016-04-22 at 9 13 29 am](https://cloud.githubusercontent.com/assets/18397/14742534/c15c4f88-086a-11e6-8f4c-d3854b4460e6.png)

Going to investigate further.

**Comment by gf3** [comment]
So, after adding my own reporter I was able to verify the false positives. However I noticed that the `DOMNode` property is also never being set, so perhaps it's related to that? Anyway as it stands this doesn't work at all for me with the following configuration:

``` js
// A11y warnings
if (Config.a11yWarnings) {
  const a11y = require('react-a11y').default;
  a11y(React, ReactDom, {
    rules: {
      'button-role-space': 'warn',
      'hidden-uses-tabindex': 'warn',
      'img-uses-alt': 'warn',
      'label-uses-for': 'warn',
      'mouse-events-map-to-key-events': 'warn',
      'no-access-key': 'warn',
      'no-hash-ref': 'warn',
      'no-unsupported-elements-use-aria': 'warn',
      'onclick-uses-role': 'warn',
      'onclick-uses-tabindex': 'warn',
      'redundant-alt': 'warn',
      'tabindex-uses-button': 'warn',
      'use-onblur-not-onchange': 'warn',
      'valid-aria-role': 'warn'
    },
    reporter: o => {
      console.warn("%s: %s.\n%p", o.displayName, o.msg, o.DOMNode)
    }
  });
}
```

**Comment by romeovs** [comment]
Thanks for the bug report! I've yet to use this in production myself so I haven't been thoroughly testing it yet. Your feedback is very helpful!

I fixed the testing code that seemed to overlook false positives completely and I've fixed all of the rules so they should be working now!

If you check if it works for you I can close this issue!

**Comment by gf3** [comment]
unfortunately it still doesn't seem to be working correctly

![screen shot 2016-04-25 at 9 35 35 am](https://cloud.githubusercontent.com/assets/18397/14785493/138a1802-0ac9-11e6-904d-694700c06f35.png)

`DOMNode` is still not reporting, and getting warnings for elements that shouldn't have any :(

**Comment by gf3** [comment]
so I think they appear on a parent component when a child component has warnings

**Comment by erin-doyle** [comment]
@gf3 is this still happening?

**Comment by gf3** [comment]
unfortunately i don't have any available time to retest this issue

**Comment by erin-doyle** [comment]
I'm closing this for now, if the issue is still happening please open a new issue.
